## Numpy Arrays

**python objects:** 

1. high-level objects: integers, floating point
2. containers: lists(costless insertion and append), dictionaries(fast lookup)

**Numpy provies:**
1. extension package to python for multi-dimensional arrays
2. closer to hardware(efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

In [3]:
import numpy as np
a = np.array([0,1,2,3,4])
print(a)

print(np.arange(10))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


**Why it is useful:** Memory efficient container that provieds fast numerical operations

In [4]:
#Python lists

L = range(1000)
%timeit [i**2 for i in L ]

447 µs ± 11.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a = np.arange(1000)
%timeit a**2

2.54 µs ± 350 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Creating arrays

In [7]:
#1-D

a = np.array([0,1,2,3,4])

a

array([0, 1, 2, 3, 4])

In [8]:
# print dimensions
a.ndim

1

In [9]:
#shape

a.shape

(5,)

In [10]:
#2-D, 3-D.....

b= np.array([[0,1,2,3],[4,5,6,7]])

b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 4)

In [13]:
len(b)

2

In [14]:
#3-D

c = np.array([[[0,1],[2,3]], [[4,5],[6,7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
c.ndim

3

In [16]:
c.shape


(2, 2, 2)

#### 1.2 Functions for creating arrays

In [19]:
# using arrange function

# arrange is an array-valued version fo the buit-in Python range function

a = np.arange(10) #0....n-1

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b = np.arange(1, 10, 2) # start, end (exclusive), step

b 

array([1, 3, 5, 7, 9])

In [25]:
# using linespace

a = np.linspace(0, 1, 4) # start, end, number of points

a

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [26]:
# common arrays

a = np.ones((3,3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
b = np.zeros((3,3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
a = np.eye(3,2) # 3 is number of rows and 2 is number of columns, index of diagnonal 
a    

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [34]:
#create array using diag function

a = np.diag([1,2,3,4])

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [35]:
np.diag(a)

array([1, 2, 3, 4])

In [36]:
# create array using random

#create an array of the given shape and populate it with random samples from
a = np.random.rand(4)

a

array([0.79201727, 0.37955393, 0.0540767 , 0.57937291])

In [37]:
a = np.random.randn(4)

a

array([ 0.12959914, -0.63049104,  0.39888115,  0.4236282 ])

In [38]:
a = np.arange(10)

a.dtype

dtype('int64')

In [39]:
# you can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')

a

# by default is float data type

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [42]:
d = np.array([1+2j, 2+4j])

print(d.dtype)

complex128


## 3. Indexing and Slicing

#### 3.1 Indexing