## Numpy Arrays

**python objects:** 

1. high-level objects: integers, floating point
2. containers: lists(costless insertion and append), dictionaries(fast lookup)

**Numpy provies:**
1. extension package to python for multi-dimensional arrays
2. closer to hardware(efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

In [3]:
import numpy as np
a = np.array([0,1,2,3,4])
print(a)

print(np.arange(10))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


**Why it is useful:** Memory efficient container that provieds fast numerical operations

In [4]:
#Python lists

L = range(1000)
%timeit [i**2 for i in L ]

447 µs ± 11.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a = np.arange(1000)
%timeit a**2

2.54 µs ± 350 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Creating arrays

In [7]:
#1-D

a = np.array([0,1,2,3,4])

a

array([0, 1, 2, 3, 4])

In [8]:
# print dimensions
a.ndim

1

In [9]:
#shape

a.shape

(5,)

In [10]:
#2-D, 3-D.....

b= np.array([[0,1,2,3],[4,5,6,7]])

b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 4)

In [13]:
len(b)

2

In [14]:
#3-D

c = np.array([[[0,1],[2,3]], [[4,5],[6,7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
c.ndim

3

In [16]:
c.shape


(2, 2, 2)

#### 1.2 Functions for creating arrays

In [ ]:
# using arrange function

# arrange is an array-valued 